# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main    # or whatever your default branch is

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/my-portfolio-site

            # 1) Sync with origin/main no matter what
            git fetch origin main
            git reset --hard origin/main

            # 2) Rebuild the Docker image
            docker build -t portfolio-site .

            # 3) Kill any container binding port 80
            docker ps -q --filter "publish=80" \
              | xargs -r docker rm -f || true

            # 4) Start fresh
            docker run -d --name portfolio-container -p 80:80 portfolio-site
          EOF
