- name: Deploy to EC2
  run: |
    ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
      cd ~/my-portfolio-site

      # 1) Sync with origin/main
      git fetch origin main
      git reset --hard origin/main

      # 2) Rebuild the Docker image
      docker build -t portfolio-site .

      # 3) Stop and remove old container if it exists
      docker rm -f portfolio-container || true

      # 4) Start fresh
      docker run -d --name portfolio-container -p 80:80 portfolio-site
    EOF
