name: Deploy to EC2 and S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- keep your original SSH deploy to EC2 ---
      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2 (SSH)
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/my-portfolio-site
            git fetch origin main
            git reset --hard origin/main
            docker build -t portfolio-site .
            docker rm -f portfolio-container || true
            docker run -d --name portfolio-container -p 80:80 portfolio-site
          EOF

      # --- OIDC: short-lived AWS creds from the role Terraform created ---
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}  # set this secret to terraform output gha_role_arn
          aws-region: us-east-1

            # --- Hardened AWS CLI install (retry + integrity check) ---
      - name: Setup AWS CLI
        uses: aws-actions/setup-aws-cli@v2
        with:
          version: '2.x'

      # --- keep your original steps ---
      - name: Pull latest main branch
        run: |
          git pull origin main

      - name: Prepare build folder
        run: |
          mkdir -p build
          cp index.html build/ || echo "index.html not found"
          cp style.css build/ || echo "style.css not found"

      # --- S3 sync now uses the assumed role (no static keys) ---
      - name: Sync to S3 bucket (OIDC creds)
        run: |
          if [ -d "./build" ]; then
            aws s3 sync ./build/ s3://tarun-portfolio-final-site/ --delete --region us-east-1
          else
            echo "⚠️ No ./build folder found. Skipping S3 sync."
          fi
