name: Deploy to EC2

on:
  push:
    branches:
      - main  # or change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/my-portfolio-site
            git pull origin main
            docker build -t portfolio-site .
            docker stop portfolio-container || true
            docker rm portfolio-container || true
            docker run -d --name portfolio-container -p 80:80 portfolio-site
          EOF


