name: Deploy to EC2 and S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/my-portfolio-site
            git fetch origin main
            git reset --hard origin/main
            docker build -t portfolio-site .
            docker rm -f portfolio-container || true
            docker run -d --name portfolio-container -p 80:80 portfolio-site
          EOF

      # ────────────────────────────────────────────────────────
      # New steps start here:
      # ────────────────────────────────────────────────────────

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python3 -m pip install --upgrade awscli

      - name: Sync to S3 bucket
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./build/ s3://tarun-portfolio-final-site/ --delete --region us-east-1
